### ISSUE TITLE
Survey Page Submission

### ISSUE THREAD

**Issue by tkz79** [tkz79/tommyboy#84]
Being able to click submit on a survey page and have the data be recorded. 

- [x] - write controller code to receive form data #89
- [x] - Add name and id params to form fields with form helper #86 
- [x] - Create a submission table  #87  
- [x] - Create an answers table that can store each bit of data #88 
- [x] - write controller code to record form data
